global:
  smtp_from: '${SMTP_USER}' # Ваш Gmail
  smtp_smarthost: 'smtp.gmail.com:587' # SMTP Gmail
  smtp_auth_username: '${SMTP_USER}' # Ваш Gmail
  smtp_auth_password: '${SMTP_PASSWORD}' # Пароль 
  smtp_require_tls: true              # Обязательно для Gmail

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 40m
  receiver: 'gmail-alerts'

receivers:
- name: 'gmail-alerts'
  email_configs:
  - to: '${SMTP_RECEIVER}' # Куда отправлять
    send_resolved: true # Уведомлять о восстановлении
    headers:
      Subject: 'Alert' # Тема письма
